reader:
  pack_name: "query"

query_creator:
  size: 1000
  field: "content"
  query_pack_name: "query"

indexer:
  query_pack_name: "query"
  field: "content"
  response_pack_name_prefix: "passage"
  index_config:
    index_name: "elastic_indexer2"
    hosts: "localhost:9200"
    algorithm: "bm25"

writer:
  output_file: "output/results_eval.tsv"

evaluator:
  pack_name: "query"
  ground_truth_file: "data/collection_and_queries/query_doc_id.tsv"
  output_file: "output/results_dev.tsv"

reranker:
  size: 10
  pretrained_model_name: "bert-large-uncased"
  cache_dir: "models"
  query_pack_name: "query"
  field: "content"
  max_seq_length: 512